price = float(input("Enter price:"))
discount = float(input("Enter discount %:"))
discount_cal = (discount/100)
reduction = (price*discount_cal)
final_price = (price - reduction)
formatted_final_price = ("{:.f2}".format(final_price))
formatted_reduction = ("{:.f2}".format(reduction))
print(f"Price with discount: {formatted_final_price}")
print(f"Reduction: {formatted_reduction}")
